-- Las vistas originales no exponen UNegocio. Se filtra su fuente antes de agregar.
SELECT * INTO #ConsolidadoUnidad FROM dbo.VT_CONSOLIDADO_CAJA WHERE 1=0;
SELECT * INTO #TransferenciasUnidad FROM dbo.VT_TRANSFERENCIASCAJA WHERE 1=0;
IF @unidad=''
BEGIN
    INSERT INTO #ConsolidadoUnidad SELECT * FROM dbo.VT_CONSOLIDADO_CAJA WHERE FECHA<=@fecha;
    INSERT INTO #TransferenciasUnidad SELECT * FROM dbo.VT_TRANSFERENCIASCAJA WHERE FECHA=@fecha;
END
ELSE
BEGIN
    INSERT INTO #ConsolidadoUnidad
        (IdCajas,FECHA,CUENTA,DESCRIPCION,INGRESOS,EGRESOS,SALDO,MONEDA,COTIZACION,CpteRendido)
    SELECT a.IdCajas,a.FECHA,a.CUENTA,c.DESCRIPCION,
        SUM(a.IMPORTE * CASE WHEN a.[DEBE-HABER]='D' THEN 1 ELSE 0 END),
        SUM(a.IMPORTE * CASE WHEN a.[DEBE-HABER]='H' THEN 1 ELSE 0 END),
        SUM(a.IMPORTE * CASE WHEN a.[DEBE-HABER]='D' THEN 1 ELSE -1 END),
        a.MONEDA,a.COTIZACION,a.CpteRendido
    FROM dbo.V_COBRANZASPORUSUARIO a INNER JOIN dbo.MA_CUENTAS c ON c.CODIGO=a.CUENTA
    WHERE LTRIM(RTRIM(a.UNEGOCIO))=@unidad AND a.FECHA<=@fecha
    GROUP BY a.IdCajas,a.FECHA,a.CUENTA,c.DESCRIPCION,a.MONEDA,a.COTIZACION,a.CpteRendido;

    -- La salida corresponde al local seleccionado. Se conserva el destino aunque sea otro local.
    INSERT INTO #TransferenciasUnidad (FECHA,CUENTA,DESCRIPCION,Egreso,Ingreso,Origen,Destino,Moneda,Cotizacion)
    SELECT a.FECHA,a.CUENTA,c.DESCRIPCION,a.Importe,b.Importe,a.IdCajas,b.IdCajas,a.MONEDA,a.COTIZACION
    FROM (SELECT TC,SUCURSAL,NUMERO,LETRA,IdCajas,CUENTA,FECHA,MONEDA,COTIZACION,SUM(IMPORTE) Importe
          FROM dbo.MV_ASIENTOS WHERE [DEBE-HABER]='H' AND FECHA=@fecha AND LTRIM(RTRIM(UNEGOCIO))=@unidad
          GROUP BY TC,SUCURSAL,NUMERO,LETRA,IdCajas,CUENTA,FECHA,MONEDA,COTIZACION) a
    INNER JOIN (SELECT TC,SUCURSAL,NUMERO,LETRA,IdCajas,CUENTA,MONEDA,COTIZACION,SUM(IMPORTE) Importe
          FROM dbo.MV_ASIENTOS WHERE [DEBE-HABER]='D'
          GROUP BY TC,SUCURSAL,NUMERO,LETRA,IdCajas,CUENTA,MONEDA,COTIZACION) b
      ON a.IdCajas<>b.IdCajas AND a.CUENTA=b.CUENTA AND a.TC=b.TC AND a.SUCURSAL=b.SUCURSAL
        AND a.NUMERO=b.NUMERO AND a.LETRA=b.LETRA AND a.MONEDA=b.MONEDA AND a.COTIZACION=b.COTIZACION
    INNER JOIN dbo.MA_CUENTAS c ON c.CODIGO=a.CUENTA
    WHERE ISNULL(c.MedioDePago,'')<>'';
END;
