IF OBJECT_ID(N'dbo.INT_COMPROBANTE_RECIBIDO', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.INT_COMPROBANTE_RECIBIDO', 'LoteId') IS NULL
    BEGIN
        ALTER TABLE dbo.INT_COMPROBANTE_RECIBIDO
        ADD LoteId uniqueidentifier NULL;
    END;
END;
GO
