/*
Carga de Viaje based on TA_CONFIGURACION.

Objective:
- create individual keys to enable additional charges
- create individual keys to add to freight driver amounts
- create the general tariff code key
- keep the legacy additional-count key for compatibility
*/

IF OBJECT_ID(N'dbo.TA_CONFIGURACION', N'U') IS NULL
    RETURN;

DECLARE @Grupo sysname = N'VIAJES';
DECLARE @LegacyCount int = 3;
DECLARE @LegacyRaw nvarchar(150);
DECLARE @LegacyTrimmed nvarchar(150);
DECLARE @LegacyValue int;

SELECT TOP (1) @LegacyRaw = VALOR
FROM dbo.TA_CONFIGURACION
WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-PORCENTAJES-ADICIONALES-HABILITADOS';

-- TRY_CONVERT no existe antes de SQL Server 2012 (compatibilidad SQL 2008 R2):
-- se valida a mano que sea solo dígitos y de largo acotado antes de convertir,
-- para no arriesgar un error de conversión ni un overflow de int.
SET @LegacyTrimmed = LTRIM(RTRIM(ISNULL(@LegacyRaw, N'')));

IF @LegacyTrimmed <> N''
   AND LEN(@LegacyTrimmed) <= 9
   AND @LegacyTrimmed NOT LIKE N'%[^0-9]%'
BEGIN
    SET @LegacyValue = CONVERT(int, @LegacyTrimmed);

    IF @LegacyValue > 0
        SET @LegacyCount = CASE WHEN @LegacyValue > 5 THEN 5 ELSE @LegacyValue END;
END;

IF @LegacyCount IS NULL OR @LegacyCount <= 0
    SET @LegacyCount = 3;

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-HABILITAR-ADICIONAL-1'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-HABILITAR-ADICIONAL-1', CASE WHEN @LegacyCount >= 1 THEN N'true' ELSE N'false' END, NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-HABILITAR-ADICIONAL-2'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-HABILITAR-ADICIONAL-2', CASE WHEN @LegacyCount >= 2 THEN N'true' ELSE N'false' END, NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-HABILITAR-ADICIONAL-3'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-HABILITAR-ADICIONAL-3', CASE WHEN @LegacyCount >= 3 THEN N'true' ELSE N'false' END, NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-HABILITAR-ADICIONAL-4'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-HABILITAR-ADICIONAL-4', CASE WHEN @LegacyCount >= 4 THEN N'true' ELSE N'false' END, NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-HABILITAR-ADICIONAL-5'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-HABILITAR-ADICIONAL-5', CASE WHEN @LegacyCount >= 5 THEN N'true' ELSE N'false' END, NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-ADICIONAL-1-SUMAR-FLETERO'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-ADICIONAL-1-SUMAR-FLETERO', N'false', NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-ADICIONAL-2-SUMAR-FLETERO'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-ADICIONAL-2-SUMAR-FLETERO', N'false', NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-ADICIONAL-3-SUMAR-FLETERO'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-ADICIONAL-3-SUMAR-FLETERO', N'false', NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-ADICIONAL-4-SUMAR-FLETERO'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-ADICIONAL-4-SUMAR-FLETERO', N'false', NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-ADICIONAL-5-SUMAR-FLETERO'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-ADICIONAL-5-SUMAR-FLETERO', N'false', NULL, GETDATE());

IF NOT EXISTS (
    SELECT 1
    FROM dbo.TA_CONFIGURACION
    WHERE UPPER(LTRIM(RTRIM(CLAVE))) = N'VIAJES-CODIGO-TARIFA-GENERAL'
)
    INSERT INTO dbo.TA_CONFIGURACION (GRUPO, CLAVE, VALOR, DESCRIPCION, FechaHora_Grabacion)
    VALUES (@Grupo, N'VIAJES-CODIGO-TARIFA-GENERAL', N'', N'Codigo de tarifa general', GETDATE());
