-- ============================================================
-- Carga de Viajes - tabla base MV_VIAJES_CARGA
-- Crea la tabla principal del modulo si todavia no existe.
-- Debe ejecutarse antes de los updates 2026-06-16-00X.
-- ============================================================

SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.MV_VIAJES_CARGA', N'U') IS NOT NULL
BEGIN
    RETURN;
END;
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MV_VIAJES_CARGA](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TC] [char](4) NOT NULL,
    [IDCLIENTE] [nvarchar](15) NULL,
    [IDCOMPROBANTE] [nvarchar](13) NOT NULL,
    [FECHA] [datetime] NOT NULL,
    [IDDESTINO] [nvarchar](4) NULL,
    [DESCRIPCIONDESTINO] [nvarchar](250) NULL,
    [IDTIPOVEHICULO] [nvarchar](4) NULL,
    [IDLISTA] [nvarchar](4) NULL,
    [IDCHOFER] [nvarchar](4) NULL,
    [NOMBRE_CHOFER] [nvarchar](100) NULL,
    [OBSERVACIONES] [nvarchar](500) NULL,
    [FECHA_FINALIZACION] [smalldatetime] NULL,
    [PATENTE] [nvarchar](10) NULL,
    [PATENTE_SEMI] [nvarchar](10) NULL,
    [ANULADO] [bit] NOT NULL,
    [ESTADO] [nvarchar](20) NOT NULL,
    [TOTAL_IMPORTE] [money] NULL,
    [TOTAL_FLETE] [money] NULL,
    [TOTAL_PEAJE] [money] NULL,
    [TOTAL_VIAJES] [float] NULL,
    [PORCENTAJE_ADIC] [money] NULL,
    [PORCENTAJE_ADIC1] [money] NULL,
    [PORCENTAJE_ADIC2] [money] NULL,
    [PORCENTAJE_ADIC3] [money] NULL,
    [PORCENTAJE_ADIC4] [money] NULL,
    [TOTAL_ADIC] [money] NULL,
    [TOTAL_ADIC1] [money] NULL,
    [TOTAL_ADIC2] [money] NULL,
    [TOTAL_ADIC3] [money] NULL,
    [TOTAL_ADIC4] [money] NULL,
    [TOTAL_ADICIONALES] [money] NULL,
    [UNEGOCIO_DESTINO] [nvarchar](4) NULL,
    [FECHAHORA_ALTA] [datetime] NULL,
    [FECHAHORA_MODIFICACION] [datetime] NULL,
    [FLETE_PAGADO] [bit] NOT NULL,
    [FECHA_PAGO_FLETE] [smalldatetime] NULL,
    [USUARIO_PAGO_FLETE] [nvarchar](50) NULL,
    [OBSERVACION_PAGO_FLETE] [nvarchar](250) NULL,
    [ADICIONAL_FIJO1_DESCRIPCION] [nvarchar](100) NULL,
    [ADICIONAL_FIJO1_IMPORTE] [money] NOT NULL,
    [ADICIONAL_FIJO1_APLICADO] [bit] NOT NULL,
    [ADICIONAL_FIJO2_DESCRIPCION] [nvarchar](100) NULL,
    [ADICIONAL_FIJO2_IMPORTE] [money] NOT NULL,
    [ADICIONAL_FIJO2_APLICADO] [bit] NOT NULL,
    [ADICIONAL_FIJO3_DESCRIPCION] [nvarchar](100) NULL,
    [ADICIONAL_FIJO3_IMPORTE] [money] NOT NULL,
    [ADICIONAL_FIJO3_APLICADO] [bit] NOT NULL,
    [TOTAL_ADICIONALES_FIJOS] [money] NOT NULL,
 CONSTRAINT [PK_MV_VIAJES_CARGA] PRIMARY KEY CLUSTERED
(
    [ID] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_TC] DEFAULT ('VJ') FOR [TC]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ANULADO] DEFAULT ((0)) FOR [ANULADO]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ESTADO] DEFAULT ('PENDIENTE') FOR [ESTADO]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_IMPORTE] DEFAULT ((0)) FOR [TOTAL_IMPORTE]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_FLETE] DEFAULT ((0)) FOR [TOTAL_FLETE]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_PEAJE] DEFAULT ((0)) FOR [TOTAL_PEAJE]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_VIAJES] DEFAULT ((1)) FOR [TOTAL_VIAJES]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_PORC0] DEFAULT ((0)) FOR [PORCENTAJE_ADIC]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_PORC1] DEFAULT ((0)) FOR [PORCENTAJE_ADIC1]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_PORC2] DEFAULT ((0)) FOR [PORCENTAJE_ADIC2]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_PORC3] DEFAULT ((0)) FOR [PORCENTAJE_ADIC3]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_PORC4] DEFAULT ((0)) FOR [PORCENTAJE_ADIC4]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADIC0] DEFAULT ((0)) FOR [TOTAL_ADIC]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADIC1] DEFAULT ((0)) FOR [TOTAL_ADIC1]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADIC2] DEFAULT ((0)) FOR [TOTAL_ADIC2]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADIC3] DEFAULT ((0)) FOR [TOTAL_ADIC3]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADIC4] DEFAULT ((0)) FOR [TOTAL_ADIC4]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADICTOTAL] DEFAULT ((0)) FOR [TOTAL_ADICIONALES]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_FLETE_PAGADO] DEFAULT ((0)) FOR [FLETE_PAGADO]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_IMPORTE] DEFAULT ((0)) FOR [ADICIONAL_FIJO1_IMPORTE]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_APLICADO] DEFAULT ((0)) FOR [ADICIONAL_FIJO1_APLICADO]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_IMPORTE] DEFAULT ((0)) FOR [ADICIONAL_FIJO2_IMPORTE]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_APLICADO] DEFAULT ((0)) FOR [ADICIONAL_FIJO2_APLICADO]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_IMPORTE] DEFAULT ((0)) FOR [ADICIONAL_FIJO3_IMPORTE]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_APLICADO] DEFAULT ((0)) FOR [ADICIONAL_FIJO3_APLICADO]
GO

ALTER TABLE [dbo].[MV_VIAJES_CARGA] ADD CONSTRAINT [DF_MV_VIAJES_CARGA_TOTAL_ADICIONALES_FIJOS] DEFAULT ((0)) FOR [TOTAL_ADICIONALES_FIJOS]
GO
