SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.TA_TARIFA', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.TA_TARIFA', 'AdicionalFijo1Descripcion') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo1Descripcion nvarchar(100) NULL;

    IF COL_LENGTH('dbo.TA_TARIFA', 'AdicionalFijo1Importe') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo1Importe money NOT NULL CONSTRAINT DF_TA_TARIFA_AdicionalFijo1Importe DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.TA_TARIFA', 'AdicionalFijo2Descripcion') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo2Descripcion nvarchar(100) NULL;

    IF COL_LENGTH('dbo.TA_TARIFA', 'AdicionalFijo2Importe') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo2Importe money NOT NULL CONSTRAINT DF_TA_TARIFA_AdicionalFijo2Importe DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.TA_TARIFA', 'AdicionalFijo3Descripcion') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo3Descripcion nvarchar(100) NULL;

    IF COL_LENGTH('dbo.TA_TARIFA', 'AdicionalFijo3Importe') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo3Importe money NOT NULL CONSTRAINT DF_TA_TARIFA_AdicionalFijo3Importe DEFAULT(0) WITH VALUES;
END;

IF OBJECT_ID(N'dbo.MV_VIAJES_CARGA', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO1_DESCRIPCION') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_DESCRIPCION nvarchar(100) NULL;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO1_IMPORTE') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_IMPORTE money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_IMPORTE DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO1_APLICADO') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_APLICADO bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_APLICADO DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO2_DESCRIPCION') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_DESCRIPCION nvarchar(100) NULL;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO2_IMPORTE') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_IMPORTE money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_IMPORTE DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO2_APLICADO') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_APLICADO bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_APLICADO DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO3_DESCRIPCION') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_DESCRIPCION nvarchar(100) NULL;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO3_IMPORTE') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_IMPORTE money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_IMPORTE DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO3_APLICADO') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_APLICADO bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_APLICADO DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'TOTAL_ADICIONALES_FIJOS') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD TOTAL_ADICIONALES_FIJOS money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_TOTAL_ADICIONALES_FIJOS DEFAULT(0) WITH VALUES;
END;
