IF OBJECT_ID(N'dbo.MV_VIAJES_CARGA', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'PORCENTAJE_ADIC5') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD PORCENTAJE_ADIC5 money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_PORCENTAJE_ADIC5 DEFAULT (0) WITH VALUES;

    IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'TOTAL_ADIC5') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD TOTAL_ADIC5 money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_TOTAL_ADIC5 DEFAULT (0) WITH VALUES;
END
