SET NOCOUNT ON;

IF COL_LENGTH(N'dbo.TA_CHOFERES', N'ES_FLETERO') IS NULL
BEGIN
    ALTER TABLE dbo.TA_CHOFERES
    ADD ES_FLETERO bit NOT NULL
        CONSTRAINT DF_TA_CHOFERES_ES_FLETERO DEFAULT (0);
END;
GO
