SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.TICK_TICKETS', N'U') IS NULL
BEGIN
    RETURN;
END;
GO

IF OBJECT_ID(N'dbo.TICK_ETIQUETAS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TICK_ETIQUETAS
    (
        IdEtiqueta int IDENTITY(1,1) NOT NULL,
        Nombre nvarchar(60) NOT NULL,
        Color nvarchar(20) NULL,
        Activa bit NOT NULL CONSTRAINT DF_TICK_ETIQUETAS_Activa DEFAULT (1),
        CONSTRAINT PK_TICK_ETIQUETAS PRIMARY KEY CLUSTERED (IdEtiqueta),
        CONSTRAINT UQ_TICK_ETIQUETAS_Nombre UNIQUE NONCLUSTERED (Nombre)
    );
END;
GO

IF OBJECT_ID(N'dbo.TICK_TICKET_ETIQUETAS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TICK_TICKET_ETIQUETAS
    (
        IdTicket bigint NOT NULL,
        IdEtiqueta int NOT NULL,
        CONSTRAINT PK_TICK_TICKET_ETIQUETAS PRIMARY KEY CLUSTERED (IdTicket, IdEtiqueta),
        CONSTRAINT FK_TICK_TICKET_ETIQUETAS_TICKET FOREIGN KEY (IdTicket) REFERENCES dbo.TICK_TICKETS (IdTicket),
        CONSTRAINT FK_TICK_TICKET_ETIQUETAS_ETIQUETA FOREIGN KEY (IdEtiqueta) REFERENCES dbo.TICK_ETIQUETAS (IdEtiqueta)
    );
END;
GO

IF COL_LENGTH(N'dbo.TICK_ETIQUETAS', N'Activa') IS NULL
BEGIN
    ALTER TABLE dbo.TICK_ETIQUETAS
        ADD Activa bit NOT NULL CONSTRAINT DF_TICK_ETIQUETAS_Activa DEFAULT (1);
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.TICK_ETIQUETAS WHERE Nombre = N'Soporte')
    INSERT INTO dbo.TICK_ETIQUETAS (Nombre, Color, Activa) VALUES (N'Soporte', N'#38BDF8', 1);

IF NOT EXISTS (SELECT 1 FROM dbo.TICK_ETIQUETAS WHERE Nombre = N'Capacitacion')
    INSERT INTO dbo.TICK_ETIQUETAS (Nombre, Color, Activa) VALUES (N'Capacitacion', N'#8B5CF6', 1);

IF NOT EXISTS (SELECT 1 FROM dbo.TICK_ETIQUETAS WHERE Nombre = N'Programacion')
    INSERT INTO dbo.TICK_ETIQUETAS (Nombre, Color, Activa) VALUES (N'Programacion', N'#14B8A6', 1);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TICK_TICKET_ETIQUETAS') AND name = N'IX_TICK_TICKET_ETIQUETAS_Etiqueta')
    CREATE NONCLUSTERED INDEX IX_TICK_TICKET_ETIQUETAS_Etiqueta ON dbo.TICK_TICKET_ETIQUETAS (IdEtiqueta, IdTicket);
GO
