SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.TA_TARIFA', N'U') IS NULL
BEGIN
    RETURN;
END;
GO

IF COL_LENGTH(N'dbo.TA_TARIFA', N'USUARIOMODIFICACION') IS NULL
BEGIN
    ALTER TABLE dbo.TA_TARIFA
        ADD USUARIOMODIFICACION nvarchar(50) NULL;
END;
GO
