SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.MV_VIAJES_CARGA', N'U') IS NULL
BEGIN
    RETURN;
END;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'IMPORTE_CLIENTE') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD IMPORTE_CLIENTE money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_IMPORTE_CLIENTE DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'IMPORTE_FLETERO') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD IMPORTE_FLETERO money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_IMPORTE_FLETERO DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'PORCENTAJE_ADIC5') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD PORCENTAJE_ADIC5 money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_PORCENTAJE_ADIC5 DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'TOTAL_ADIC5') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD TOTAL_ADIC5 money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_TOTAL_ADIC5 DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO1_PIDE_CANTIDAD') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_PIDE_CANTIDAD bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_PIDE_CANTIDAD DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO1_CANTIDAD') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_CANTIDAD decimal(18,2) NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_CANTIDAD DEFAULT (1) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO2_PIDE_CANTIDAD') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_PIDE_CANTIDAD bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_PIDE_CANTIDAD DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO2_CANTIDAD') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_CANTIDAD decimal(18,2) NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_CANTIDAD DEFAULT (1) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO3_PIDE_CANTIDAD') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_PIDE_CANTIDAD bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_PIDE_CANTIDAD DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO3_CANTIDAD') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_CANTIDAD decimal(18,2) NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_CANTIDAD DEFAULT (1) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO1_IMPORTE_FLETERO') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_IMPORTE_FLETERO money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_IMPORTE_FLETERO DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO2_IMPORTE_FLETERO') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_IMPORTE_FLETERO money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_IMPORTE_FLETERO DEFAULT (0) WITH VALUES;

IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO3_IMPORTE_FLETERO') IS NULL
    ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_IMPORTE_FLETERO money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_IMPORTE_FLETERO DEFAULT (0) WITH VALUES;
