IF OBJECT_ID(N'dbo.MV_VIAJES_CARGA', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO1_PIDE_CANTIDAD') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_PIDE_CANTIDAD bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_PIDE_CANTIDAD DEFAULT (0) WITH VALUES;

    IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO2_PIDE_CANTIDAD') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_PIDE_CANTIDAD bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_PIDE_CANTIDAD DEFAULT (0) WITH VALUES;

    IF COL_LENGTH(N'dbo.MV_VIAJES_CARGA', N'ADICIONAL_FIJO3_PIDE_CANTIDAD') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_PIDE_CANTIDAD bit NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_PIDE_CANTIDAD DEFAULT (0) WITH VALUES;
END;
GO

IF OBJECT_ID(N'dbo.TA_TARIFA', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH(N'dbo.TA_TARIFA', N'AdicionalFijo1PideCantidad') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo1PideCantidad bit NOT NULL CONSTRAINT DF_TA_TARIFA_AdicionalFijo1PideCantidad DEFAULT (0) WITH VALUES;

    IF COL_LENGTH(N'dbo.TA_TARIFA', N'AdicionalFijo2PideCantidad') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo2PideCantidad bit NOT NULL CONSTRAINT DF_TA_TARIFA_AdicionalFijo2PideCantidad DEFAULT (0) WITH VALUES;

    IF COL_LENGTH(N'dbo.TA_TARIFA', N'AdicionalFijo3PideCantidad') IS NULL
        ALTER TABLE dbo.TA_TARIFA ADD AdicionalFijo3PideCantidad bit NOT NULL CONSTRAINT DF_TA_TARIFA_AdicionalFijo3PideCantidad DEFAULT (0) WITH VALUES;
END;
GO
