IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebSessionMode') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebSessionMode nvarchar(30) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebPhoneNumber') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebPhoneNumber nvarchar(50) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebSessionStatus') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebSessionStatus nvarchar(30) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebDisplayName') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebDisplayName nvarchar(100) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebInstanceName') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebInstanceName nvarchar(100) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebPairingToken') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebPairingToken nvarchar(100) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebPairingCode') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebPairingCode nvarchar(50) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebPairingQrPayload') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebPairingQrPayload nvarchar(max) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebPairingGeneratedAtUtc') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebPairingGeneratedAtUtc datetime NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebPairingExpiresAtUtc') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebPairingExpiresAtUtc datetime NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebRuntimeState') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebRuntimeState nvarchar(50) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebLastError') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebLastError nvarchar(500) NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebWorkerProcessId') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebWorkerProcessId int NULL;

IF COL_LENGTH('dbo.CONV_WHATSAPP_NUMEROS', 'WebRuntimeUpdatedAtUtc') IS NULL
    ALTER TABLE dbo.CONV_WHATSAPP_NUMEROS ADD WebRuntimeUpdatedAtUtc datetime NULL;
GO

UPDATE dbo.CONV_WHATSAPP_NUMEROS
SET
    WebSessionMode = ISNULL(NULLIF(LTRIM(RTRIM(WebSessionMode)), ''), 'QR'),
    WebSessionStatus = ISNULL(NULLIF(LTRIM(RTRIM(WebSessionStatus)), ''), 'DISCONNECTED')
WHERE
    ISNULL(NULLIF(LTRIM(RTRIM(WebSessionMode)), ''), '') = ''
    OR ISNULL(NULLIF(LTRIM(RTRIM(WebSessionStatus)), ''), '') = '';
