SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.MV_VIAJES_CARGA', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO1_IMPORTE_FLETERO') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO1_IMPORTE_FLETERO money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO1_IMPORTE_FLETERO DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO2_IMPORTE_FLETERO') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO2_IMPORTE_FLETERO money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO2_IMPORTE_FLETERO DEFAULT(0) WITH VALUES;

    IF COL_LENGTH('dbo.MV_VIAJES_CARGA', 'ADICIONAL_FIJO3_IMPORTE_FLETERO') IS NULL
        ALTER TABLE dbo.MV_VIAJES_CARGA ADD ADICIONAL_FIJO3_IMPORTE_FLETERO money NOT NULL CONSTRAINT DF_MV_VIAJES_CARGA_ADICIONAL_FIJO3_IMPORTE_FLETERO DEFAULT(0) WITH VALUES;
END;
GO
