IF OBJECT_ID('dbo.CO_CPTES_IMPAGOS_2026', 'V') IS NOT NULL
BEGIN
    DROP VIEW [dbo].[CO_CPTES_IMPAGOS_2026]
END
GO

/****** Object:  View [dbo].[CO_CPTES_IMPAGOS_2026]    Script Date: 17/4/2026 10:30:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[CO_CPTES_IMPAGOS_2026]
AS
WITH CFG AS
(
    SELECT TOP (1)
        VALOR AS CUENTA_CF
    FROM dbo.TA_CONFIGURACION
    WHERE CLAVE = N'CUENTAPROVEEDORESVARIOS'
)
SELECT
    COALESCE(V.VENCIMIENTO, V.FECHA) AS VENCIMIENTO,
    V.FECHA,
    V.CUENTA,
    COALESCE(NULLIF(LTRIM(RTRIM(V.CABNOMBRE)), N''), M.DESCRIPCION) AS NOMBRE,
    V.TC,
    V.SUCURSAL,
    V.NUMERO,
    V.LETRA,
    V.IMPORTE,
    V.PAGO,
    V.SALDO,
    V.UNEGOCIO,
    V.SUCURSAL + V.NUMERO + V.LETRA AS IDCOMPROBANTE
FROM dbo.CO_CPTES_IMPAGOS V
LEFT JOIN dbo.MA_CUENTAS M
    ON V.CUENTA = M.CODIGO
CROSS JOIN CFG
WHERE
    V.TC IN (N'FCC', N'FPC', N'NDC')
    AND (CFG.CUENTA_CF IS NULL OR V.CUENTA <> CFG.CUENTA_CF);
GO


