 
IF OBJECT_ID('CO_PAGOS_REALIZADOS', 'V') IS NOT NULL
BEGIN
	DROP VIEW [dbo].[CO_PAGOS_REALIZADOS]
END  
GO

/****** Object:  View [dbo].[CO_PAGOS_REALIZADOS]    Script Date: 17/4/2026 17:41:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[CO_PAGOS_REALIZADOS]
AS
SELECT A.FECHA, A.TC, ISNULL(A.SUCURSAL, N'') + ISNULL(A.NUMERO, N'') + ISNULL(A.LETRA, N'') AS idcomprobante, A.CUENTA, COALESCE (A.CABNOMBRE, C.DESCRIPCION) AS NOMBRE, A.[DEBE-HABER], A.IMPORTE, A.MONEDA, 
                  A.COTIZACION, A.DETALLE, A.FechaHora_Grabacion, A.USUARIO_LOGEADO AS USUARIO
FROM     dbo.MV_ASIENTOS AS A LEFT OUTER JOIN
                  dbo.MA_CUENTAS AS C ON A.CUENTA = C.CODIGO
WHERE  (A.TC IN ('pg', 'opg', 'PGFP')) AND (A.SECUENCIA = 1)
GO
 