 

CREATE NONCLUSTERED INDEX IX_CONTROL_ACCESO_Usuario_Tarea_Ingreso
ON dbo.CONTROL_ACCESO (USUARIO, TAREA, INGRESO);
GO

CREATE NONCLUSTERED INDEX IX_CONTROL_ACCESO_Usuario_Ingreso
ON dbo.CONTROL_ACCESO (USUARIO, INGRESO);
GO

CREATE NONCLUSTERED INDEX IX_TA_MENU_Menu_Nombre
ON dbo.TA_MENU (Menu, Nombre)
INCLUDE (Clave, Proceso);
GO