 
  

/****** Object:  View [dbo].[VE_CPTES_SALDOS_VENTAS]    Script Date: 10/4/2026 07:39:15 ******/
IF OBJECT_ID('dbo.VE_CPTES_SALDOS_VENTAS', 'V') IS NOT NULL
BEGIN
	DROP VIEW [dbo].[VE_CPTES_SALDOS_VENTAS]
END
GO

/****** Object:  View [dbo].[VE_CPTES_SALDOS_VENTAS]    Script Date: 10/4/2026 07:39:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VE_CPTES_SALDOS_VENTAS]
AS
SELECT V.CUENTA, COALESCE (V.CABNOMBRE, M.DESCRIPCION) AS NOMBRE, V.FECHA, V.TC, V.SUCURSAL, V.NUMERO, V.LETRA, V.SALDO, ISNULL(V.Vencimiento, V.fecha) AS VENCIMIENTO, 0 AS CUOTA 
FROM     VE_CPTES_SALDOS V LEFT JOIN
                  MA_CUENTAS M ON V.CUENTA = M.CODIGO
WHERE  V.TIPOVISTA IN ('CL', 'CB', 'CM') AND V.SALDO <> 0
UNION
SELECT V.CUENTA, COALESCE (V.CABNOMBRE, M.DESCRIPCION) AS NOMBRE, V.FECHA, V.TC, V.SUCURSAL, V.NUMERO, V.LETRA, V.SALDO * - 1, ISNULL(V.Vencimiento, V.fecha) AS VENCIMIENTO, 0 AS CUOTA 

FROM     VE_CPTES_CREDITOS_PENDIENTES_SINREMITOS V LEFT JOIN
                  MA_CUENTAS M ON V.CUENTA = M.CODIGO
WHERE  V.TIPOVISTA IN ('CL', 'CB', 'CM') AND V.SALDO <> 0
GO 
